#pragma once

#include <stddef.h>
#include <stdint.h>

#define SPLASH_LOGO_WIDTH 240
#define SPLASH_LOGO_HEIGHT 231
#define SPLASH_LOGO_PADDED_WIDTH 256
#define SPLASH_TITLE_WIDTH 300
#define SPLASH_TITLE_HEIGHT 77
#define SPLASH_TITLE_PADDED_WIDTH 320
#define SPLASH_TITLE_PADDED_HEIGHT 78

// Symbols generated by psn00bsdk_target_incbin() from the CMake-built TIMs
extern const uint8_t splash_logo_tim[];
extern const size_t splash_logo_tim_size;
extern const uint8_t splash_title_tim[];
extern const size_t splash_title_tim_size;
